#!/usr/bin/bash

#Global Variables
VSSH_CLIENT="root@jeremiah.onlyirul.com"
VDOMAIN="jeremiah.onlyirul.com"
VSITEDIR="/etc/nginx/sites-available/"
VWWWROOT="/var/www/prod/"
VPUBLICDIR="public_html"

#Color
RED="\e[31m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

#Status
SUCCESS="[${GREEN}OK${ENDCOLOR}]"
FAIL="[${RED}FAIL${ENDCOLOR}]"

#SSH Function
remote() {
        ssh -q $VSSH_CLIENT exit
}
remote_cmd() {
        ssh -q $VSSH_CLIENT "$1"
}

echo -e "--------------------------------------------------------------------------------------"
echo -e "                  Creating virtual host With Automation Tool "
echo -e "--------------------------------------------------------------------------------------"

# domain name for virtual host
while [[ -z "$VSUBDOMAIN" ]]
do
        read -p "What subdomain name that you want to use? " VSUBDOMAIN
        VDOCROOT="${VWWWROOT}${VSUBDOMAIN}.${VDOMAIN}/${VPUBLICDIR}";
done

# check SSH
remote
if [[ ! $? -eq 0 ]]; then
        echo -e "$FAIL SSH connection failed"
        exit 1
fi

# check if the subdomain name already exists in configuration files
if remote_cmd "[ -f ${VSITEDIR}${VSUBDOMAIN}.${VDOMAIN} ]"; then
        echo -e "$FAIL Subdomain $VSUBDOMAIN already in configuration files!"
        exit 1
fi

# Create document root and set permissions
if remote_cmd "[ -d $VDOCROOT ]"; then
        echo -e "$FAIL Document root $VDOCROOT already exists"
        exit 1
else
        echo -e "$SUCCESS Domain name: $VSUBDOMAIN"
fi

remote_cmd "mkdir -p $VDOCROOT"
remote_cmd "chown -R $USER:$USER $VDOCROOT"
remote_cmd "chmod -R 755 $VDOCROOT"
echo -e "$SUCCESS Document root: $VDOCROOT"
VBOILERPLATE='<?php echo "<h1> This is '$VSUBDOMAIN' site </h1>" . "<br>"; echo "Generated by automation tool on " . date("Y/m/d"); ?>'
remote_cmd "echo '$VBOILERPLATE' > '$VDOCROOT'/index.php"

# Create Server Block
VUPSTREAM=$(sed "s/SUBDOMAIN/$VSUBDOMAIN/g" /home/gerda/upstreamtemplate)
remote_cmd "echo '$VUPSTREAM' > ${VSITEDIR}${VSUBDOMAIN}.${VDOMAIN}"
remote_cmd "ln -s ${VSITEDIR}${VSUBDOMAIN}.${VDOMAIN} /etc/nginx/sites-enabled/"
echo -e "$SUCCESS Symlink Virtual Host on /etc/nginx/sites-enabled/${VSUBDOMAIN}.${VDOMAIN}"

# restart NGINX
remote_cmd "nginx -tq"
set -o errexit
remote_cmd "nginx -s reload"
echo -e "$SUCCESS NGINX is already restarted!"

# generate output
echo -e "------------------------------------ Confirmed by ------------------------------------"
remote_cmd "nginx -T | grep $VSUBDOMAIN"
